language: go
go:
  - 1.8.x
  - 1.10.x
before_install:
  - go get -t -v ./...
  - go get github.com/rugby-board/rugby-dict-data
script:
  - ./test.sh
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email: false
